language: csharp
mono: none
dotnet: 3.1
install:
 - sudo dotnet tool install --global dotnet-ef
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE EmployeeTestDB" -U postgres
 - psql -c "CREATE USER test_account WITH PASSWORD 'test'" -U postgres
script:
 - dotnet build -c Release ./ArithematicChecks/ArithematicChecks.sln
 - dotnet-ef database update --project "./ArithematicChecks/ArithematicAPIService.v1/ArithematicAPIService.v1.csproj"
 - dotnet test -c Release --no-build ./ArithematicChecks/ArithematicChecks.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
 - bash <(curl -s https://codecov.io/bash)