language: csharp
mono: none
dotnet: 3.1
install:
 - dotnet restore ./ArithematicChecks/ArithematicChecks.sln
script:
 - dotnet build ./ArithematicChecks/ArithematicChecks.sln
 - dotnet test ./ArithematicChecks/ArithematicLibraryTests/ArithematicLibraryTests.csproj
 - dotnet coverage ./ArithematicChecks/ArithematicChecks.sln
 - bash <(curl -s https://codecov.io/bash)