language: csharp
mono: none
dotnet: 3.1
services:
 - postgresql
before_script:
 - psql -c "CREATE USER test_account WITH PASSWORD 'test';" -U postgres
 - psql -c "CREATE DATABASE EmployeeTestDB;" -U postgres
script:
 - dotnet build -c Release ./ArithematicChecks/ArithematicChecks.sln
 - dotnet ef database update ./ArithematicChecks/ArithematicChecks.sln
 - dotnet test -c Release --no-build ./ArithematicChecks/ArithematicChecks.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
 - bash <(curl -s https://codecov.io/bash)