language: csharp
sudo: required
mono: none
dotnet: 3.1
services:
- postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 9.6 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 9.6 main

env:
  global:
    - PGPORT=5432
before_script:
 - export PATH=$PATH:/home/travis/.dotnet/tools
 - dotnet tool install --global dotnet-ef
 - psql -c "CREATE USER service_account WITH PASSWORD 'service';" -U postgres
 - psql -c "CREATE DATABASE employee_db;" -U postgres
 - psql -c "GRANT ALL PRIVILEGES ON DATABASE employee_db to service_account" -U postgres
script:
 - dotnet build -c Release ./ArithematicChecks/ArithematicChecks.sln
 - dotnet-ef migrations add CreateInitial --project ./ArithematicChecks/ArithematicAPIService.v1/ArithematicAPIService.v1.csproj
 - dotnet-ef database update --project ./ArithematicChecks/ArithematicAPIService.v1/ArithematicAPIService.v1.csproj
 - dotnet test -c Release --no-build ./ArithematicChecks/ArithematicChecks.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
 - bash <(curl -s https://codecov.io/bash)