language: csharp
mono: none
dotnet: 3.1
install:
 - dotnet restore ./ArithematicChecks/ArithematicChecks.sln
script:
 - dotnet build -c Release ./ArithematicChecks/ArithematicChecks.sln
 - dotnet test -c Release --no-build ./ArithematicChecks/ArithematicLibraryTests/ArithematicLibraryTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
 - bash <(curl -s https://codecov.io/bash)